pkg/nfs/nfs.go
pkg/nfs/nodeserver.go

/kind cleanup
Allow other mounters to be used so that we can add unit tests using FakeMounter.
Fixes #
```release-note
NONE
```

Add ability to use other mounters for unit testing

---

Dockerfile

/kind cleanup
Updating the container image base to contain fewer vulnerabilities (drops from [71](https://quay.io/repository/k8scsi/nfsplugin?tag=latest&tab=tags) to [5](https://quay.io/repository/wozniakjan/nfsplugin/manifest/sha256:b4079ac1591274d831a5bb6e6418aa7a6767ae930bd4f19e7a9df0ed6ed2f52e?tab=vulnerabilities)). Also proposes to use `latest` tag as there is not really much that we use from the base image and I think it is rather unlikely to break the go binary anyways.
This changes the base from centos7 (latest 7 tag contains 7 vulnerabilities) to current centos8 (latest 8 tag contains 5 vulnerabilities). The last 5 critical vulnerabilities do not have released fixes in centos image yet and uninstalling systemd …

Change base image to centos:latest

---

deploy/kubernetes/csi-nfs-driverinfo.yaml
examples/kubernetes/nginx.yaml
pkg/nfs/nfs.go
test/nfs-testdriver.go

/kind cleanup
Changes name of the driver to follow dotted conventions established in other CSI drivers.
Fixes https://github.com/kubernetes-csi/csi-driver-nfs/issues/19
```release-note
Changing name of the driver from "csi-nfsplugin" to "nfs.csi.k8s.io"
```

Rename driver to follow CSI plugin naming conventions

---

README.md
deploy/kubernetes/csi-nodeplugin-nfsplugin.yaml
pkg/nfs/nfs.go

/kind cleanup
Informs about basic compatibility and feature set of the plugin.
Fixes: https://github.com/kubernetes-csi/csi-driver-nfs/issues/3
```release-note
NONE
```

Add basic info to README about the plugin compatibility and features

---

cmd/nfsplugin/main.go
pkg/nfs/nfs.go
pkg/nfs/nodeserver.go

/kind feature
For RWX volume, kubelet does not perform recursive ownership/permission change. The heuristics that kubelet uses is being modified via - https://github.com/kubernetes/enhancements/issues/1682
Having said that, for RWX volumes which are made available via NFS protocol, using fsGroup is not recommended because if there are 2 pods that are trying to use same volume but with different fsGroup then one pod may lock out the other pod.
To avoid this, we must be able to set the folder permissions to 777.
```release-note
Added an optional cli parameter `--mount-permissions`, that allows to define custom permissions for the mounted folder. If the value is not …
```

Allow to set custom permissions for the mounted folder

---

deploy/kubernetes/csi-nodeplugin-nfsplugin.yaml
examples/kubernetes/nginx.yaml

/kind bug
Remove hostnetwork from the driver Daemonset so that the csi driver can resolve K8s dns names.
Also clean up the example to use claimRef instead of a selector which is not as exact in matching.
Fixes #
```release-note
Fixes issue where the driver could not mount a nfs server via Kubernetes dns service name.
```

Remove hostnetwork from plugin

---

Makefile
test/sanity/README.md
test/sanity/run-test.sh

test: add sanity test
Also need to fix the sanity test failure
```
[Fail] Node Service [BeforeEach] NodePublishVolume should fail when no volume id is provided
/root/go/pkg/mod/github.com/kubernetes-csi/csi-test@v2.2.0+incompatible/pkg/sanity/sanity.go:234
[Fail] Node Service [BeforeEach] NodePublishVolume should fail when no target path is provided
/root/go/pkg/mod/github.com/kubernetes-csi/csi-test@v2.2.0+incompatible/pkg/sanity/sanity.go:234
[Fail] Node Service [BeforeEach] NodePublishVolume should fail when no volume capability is provided
/root/go/pkg/mod/github.com/kubernetes-csi/csi-test@v2.2.0+incompatible/pkg/sanity/sanity.go:234
[Fail] Node Service [BeforeEach] NodeUnpublishVolume should fail …
```

test: add sanity test

---

pkg/nfs/controllerserver.go
pkg/nfs/nodeserver.go
test/sanity/run-test.sh

/kind bug
fix: all sanity test failures
```
------------------------------
S
Ran 10 of 72 Specs in 0.204 seconds
SUCCESS! -- 10 Passed | 0 Failed | 0 Pending | 62 Skipped
```
also skipped some sanity tests which require  `CreateVolume` support, e.g.
```
[Fail] Node Service [It] should work
/root/go/pkg/mod/github.com/kubernetes-csi/csi-test@v2.2.0+incompatible/pkg/sanity/node.go:687
[Fail] Controller Service [Controller Server] ControllerGetCapabilities [It] should return appropriate capabilities
/root/go/pkg/mod/github.com/kubernetes-csi/csi-test@v2.2.0+incompatible/pkg/sanity/controller.go:143
[Fail] Controller Service [Controller Server] ValidateVolumeCapabilities [It] should fail when no volume capabilities are …
```

fix: all sanity test failures

---

examples/kubernetes/nfs-provisioner/README.md
examples/kubernetes/nfs-provisioner/nfs-server-lb.yaml
examples/kubernetes/nfs-provisioner/nfs-server.yaml
examples/kubernetes/nfs-provisioner/pv-nfs-csi.yaml

Add example for NFS provisioner

---

.gitignore
Makefile
deploy/kubernetes/csi-nfs-controller.yaml
deploy/kubernetes/rbac-csi-nfs-controller.yaml
docs/csi-dev.md

This PR adds the following:
- Add manifest for installing driver controller
- Add manifest for required RBAC
- Update Makefile for local Kubernetes install / uninstall
- Add Dockerfile and dev.Dockerfile
- Add docs on how to develop driver locally
Fixes #
```release-note
None
```

Add manifest for installing driver controller and install docs

---

charts/csi-driver-nfs/templates/csi-nfs-controller.yaml
charts/csi-driver-nfs/values.yaml
deploy/kubernetes/csi-nfs-controller.yaml

/kind bug
>
> /kind bug
> /kind design
> /kind flake
Replace livenessprobe flag --connection-timeout with --probe-timeout.
Update the livenessprobe version from v1.1.0 to v2.0.0.
Update helm charts.
Fixes #
```release-note
```

fix: update livenessprobe version from v1.1.0 to v2.0.0

---

test/e2e/dynamic_provisioning_test.go
test/e2e/e2e_suite_test.go
test/e2e/testsuites/dynamically_provisioned_collocated_pod_tester.go
test/e2e/testsuites/dynamically_provisioned_delete_pod_tester.go
test/e2e/testsuites/dynamically_provisioned_pod_with_multiple_pv.go
test/e2e/testsuites/dynamically_provisioned_read_only_volume_tester.go
test/e2e/testsuites/dynamically_provisioned_reclaim_policy_tester.go
test/e2e/testsuites/specs.go
test/e2e/testsuites/testsuites.go
test/utils/check_driver_pods_restart.sh
vendor/golang.org/x/crypto/poly1305/sum_noasm.go
vendor/golang.org/x/crypto/poly1305/sum_vmsl_s390x.s
vendor/k8s.io/kubernetes/test/e2e/framework/deployment/BUILD
vendor/k8s.io/kubernetes/test/e2e/framework/deployment/fixtures.go
vendor/k8s.io/kubernetes/test/e2e/framework/deployment/wait.go

>
> /kind bug
> /kind design
> /kind flake
Add the following E2E tests for dynamic provisioning
- DynamicallyProvisionedCollocatedPodTest
- DynamicallyProvisionedReadOnlyVolumeTest
- DynamicallyProvisionedDeletePodTest
- DynamicallyProvisionedReclaimPolicyTest
- DynamicallyProvisionedPodWithMultiplePVTest
Fixes #
```release-note
None …
```

Add E2E test cases for dynamic provisioning

---

Makefile
charts/latest/csi-driver-nfs/templates/csi-nfs-node.yaml
pkg/nfs/controllerserver.go
test/e2e/testsuites/dynamically_provisioned_reclaim_policy_tester.go

>
> /kind bug
> /kind design
> /kind flake
/kind bug
Fix internalUnmount failure because field VolumeId was missing.
Fix DeleteVolume failure: if the server is "127.0.0.1", the share is "/", then the old logic would give you a volume id "127.0.0.1///volumeName" (with three "/"). This is wrong because the volume id should be "127.0.0.1//volumeName" (with two "/") based on the path format `"workingDir/subDir/subDir`. Add trimming logic.
Skip one cleanup step in the e2e test since the controller server cannot …

fix: internalUnmount failure and DeleteVolume failure

---

charts/latest/csi-driver-nfs/templates/csi-nfs-controller.yaml
charts/latest/csi-driver-nfs/templates/csi-nfs-node.yaml
deploy/csi-nfs-controller.yaml
deploy/csi-nfs-node.yaml

/kind bug
chore: change port num
the health probe port nums are copied from smb csi driver, need to change those nums to prevent port conflict
Fixes #
```release-note
none
```

chore: change port num for health check

---

release-tools/build.make

/kind feature
Release tool update
Fixes #
```release-note
none
```

Release tool update

---

.github/workflows/static.yaml

>
> /kind bug
> /kind design
> /kind flake
Fixes #90
```release-note
None
```

CI: enable golint

---

charts/latest/csi-driver-nfs/templates/csi-nfs-node.yaml
deploy/csi-nfs-node.yaml
deploy/example/deployment.yaml
test/e2e/testsuites/testsuites.go

>
> /kind bug
> /kind design
> /kind flake
/kind bug
Only deploy the node server on Linux nodes.
Only test pods/deployments on Linux nodes.
Fixes #
```release-note
None
```

fix: limit node server to deploy only on Linux nodes

---

pkg/nfs/controllerserver_test.go
pkg/nfs/utils_test.go

/kind feature
This PR adds some of the missing unit tests for the controller server and utils in `pkg/nfs`
Fixes #121 
none
```release-note
none
```

test: Add missing unit tests for controller server and utils

---

release-tools/.prow.sh
release-tools/SIDECAR_RELEASE_PROCESS.md
release-tools/boilerplate/boilerplate.Dockerfile.txt
release-tools/boilerplate/boilerplate.Makefile.txt
release-tools/boilerplate/boilerplate.bzl.txt
release-tools/boilerplate/boilerplate.go.txt
release-tools/boilerplate/boilerplate.py
release-tools/boilerplate/boilerplate.py.txt
release-tools/boilerplate/boilerplate.sh.txt
release-tools/build.make
release-tools/cloudbuild.yaml
release-tools/prow.sh
release-tools/verify-boilerplate.sh
release-tools/verify-spelling.sh
release-tools/verify-subtree.sh

/kind cleanup
Updates the release tools for this repository after which we can enable spelling and boilerplate checks.
Part of #128 
```release-note
none
```

Update release tools

---

.prow.sh
docs/csi-dev.md
hack/verify-all.sh

/kind cleanup
Enables spelling and boilerplate checks for prow tests and in `hack/verify-all.sh` for local checks.
Fixes #128 
```release-note
none
```

Enable spelling and boilerplate checks in prow and local tests

---

.github/workflows/darwin.yaml
.github/workflows/linux.yaml
charts/latest/csi-driver-nfs/templates/csi-nfs-controller.yaml
charts/latest/csi-driver-nfs/templates/csi-nfs-node.yaml
deploy/csi-nfs-controller.yaml
deploy/csi-nfs-node.yaml
hack/verify-examples.sh
pkg/nfs/indentityserver.go
pkg/nfs/utils.go
pkg/nfs/utils_test.go

/kind bug
fix: reduce driver logs
- don't print following method logs by default
following 3 method logs constitute 99.8% logs of all driver logs, this PR set the log level of following 3 methods as `10`, and it would not show in driver logs by default(<= `5` will show in driver logs)
```
/csi.v1.Identity/Probe
/csi.v1.Node/NodeGetCapabilities
/csi.v1.Node/NodeGetVolumeStats
```
- set log level of csi side car contains as 2
This could reduce `17,280` logs every day of csi-provisioner, csi-resizer, etc which has lease election, following logs would show every 5s:
```
I0119 12:57:02.073355       1 leaderelection.go:282] successfully renewed lease kube-system/blob-csi-azure-com
I0119 12:57:07.081182       1 …
```

fix: reduce driver logs

---

release-tools/prow.sh
release-tools/verify-boilerplate.sh

Squashed 'release-tools/' changes from 9289fd1..1d60e77
[1d60e77](https://github.com/kubernetes-csi/csi-release-tools/commit/1d60e77) Merge pull request #131 from pohly/kubernetes-1.20-tag
[9f10459](https://github.com/kubernetes-csi/csi-release-tools/commit/9f10459) prow.sh: support building Kubernetes for a specific version
[fe1f284](https://github.com/kubernetes-csi/csi-release-tools/commit/fe1f284) Merge pull request #121 from kvaps/namespace-check
[8fdf0f7](https://github.com/kubernetes-csi/csi-release-tools/commit/8fdf0f7) Merge pull request #128 from fengzixu/master
[1c94220](https://github.com/kubernetes-csi/csi-release-tools/commit/1c94220) fix: fix a bug of csi-sanity
[a4c41e6](https://github.com/kubernetes-csi/csi-release-tools/commit/a4c41e6) Merge pull request #127 from …

master: update release-tools

---

Makefile
go.mod
pkg/nfs/nfs.go
pkg/nfs/version.go
pkg/nfs/version_test.go
vendor/modules.txt

/kind feature
The changes in this PR provides more information about the driver when the driver is started.
Fixes #131 
```release-note
none
```

provide more driver info in logs

---

pkg/nfs/controllerserver.go

/kind bug
This PR fixed following issue:
```
E0209 23:34:10.378470       1 utils.go:89] GRPC error: rpc error: code = Internal desc = failed to make subdirectory: mkdir /tmp/pvc-5abc9306-717c-4fba-afe5-7fcdf0439822/pvc-5abc9306-717c-4fba-afe5-7fcdf0439822: file exists
it's strange because I login to the master node where the controller is running on, and I don't find /tmp/pvc-5abc9306-717c-4fba-afe5-7fcdf0439822/pvc-5abc9306-717c-4fba-afe5-7fcdf0439822 is there
```
Fixes #
```release-note
fix: makeDir error in CreateVolume
```

fix: makeDir error in CreateVolume

---

pkg/nfs/nfs.go
pkg/nfs/nfs_test.go
pkg/nfs/nodeserver.go
pkg/nfs/nodeserver_test.go
pkg/nfs/utils.go

>
> /kind bug
> /kind design
> /kind flake
/kind feature
Add locks for Node server publish/unpublish operations.
Only add locks for Node server because Controller server internally calls Node server.
Fixes #
```release-note
none
```

feat: add locks for nodeserver publish/unpublish operations

---

Dockerfile

/kind feature
chore: change base image to debian
same as https://github.com/kubernetes-csi/csi-driver-smb/blob/a6fcf70cf8bf8ca1673147bcc9b7f7ceef29386f/pkg/smbplugin/Dockerfile#L18
Fixes #
original base image error:
```
nfs image building error:
#3 [internal] load metadata for docker.io/library/centos:latest
#3 ERROR: no match for platform in manifest sha256:5528e8b1b1719d34604c87e11dcd1c0a20bedf46e83b5632cdeac91b8c04efc1: not found
```
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/post-csi-driver-nfs-push-images/1362034346201976832
```release-note
chore: change base image to debian
```

fix: change base image to debian

---

test/e2e/dynamic_provisioning_test.go
test/e2e/e2e_suite_test.go
test/e2e/testsuites/dynamically_provisioned_volume_subpath_tester.go
test/e2e/testsuites/specs.go
test/e2e/testsuites/testsuites.go

/kind cleanup
add subPath e2e test
Fixes #162 
```release-note
none
```

add subPath e2e test

---

pkg/nfs/controllerserver.go
pkg/nfs/controllerserver_test.go

/kind bug
Currently the split in getNfsVolFromID expects that the share is just one folder like /data and not something like /data/kubernetes and fails in the later case with an unexpected amount of tokens.
This splits the id into server until the first / and subdir starting from the last / character. Everything between them is considered a part of baseDir
Fixes #184
```release-note
NONE
```

Allow shares that are not at the root

---

Makefile
test/external-e2e/run.sh
test/external-e2e/testdriver.yaml

/kind flake
Adding External e2e tests. Offers a better way to test the driver changes. 
Fixes 
```release-note
none
```

Add K8s external storage E2E tests

---

Dockerfile

/kind bug
chore: upgrade base image to fix CVE issue
Fixes #
```
2021-05-12T10:41:52.693Z        INFO    Detecting Debian vulnerabilities...
2021-05-12T10:41:52.725Z        INFO    Detecting gobinary vulnerabilities...
mcr.microsoft.com/k8s/csi/nfs-csi:latest (debian 10.5)
======================================================
Total: 7 (UNKNOWN: 0, LOW: 0, MEDIUM: 5, HIGH: 2, CRITICAL: 0)
+---------------+------------------+----------+-------------------+----------------------+---------------------------------------+
|    LIBRARY    | VULNERABILITY ID | SEVERITY | INSTALLED VERSION |    FIXED VERSION     |                 TITLE                 | …
```

chore: upgrade base image to fix CVE issue

---

pkg/nfs/controllerserver.go

Now that https://github.com/kubernetes-csi/external-provisioner/pull/271 this PR is merged, we can depend on external-provisioner to set the capacity setting automatically. 
/kind cleanup
Fixes #
```release-note
none
```

Remove capacity setting in create Volume response

---

deploy/example/README.md

deploy/example/README.md includes `storage` / `PV` / `PVC` usage  . But we can not deploy any pod/deployment/statefulset even if following to this README, so we cannot check NFS CSI driver using simple nginx sample.
This PR adds `deployment` / `statefulset` usage using hack/verify-examples.sh to README.
Fixes #
```release-note
none
```

Add usage using hack/verify-examples.sh

---

Dockerfile
Makefile

/kind feature
feat: support arm64 image build
Fixes #227 
```release-note
feat: support arm64 image build
```

feat: support arm64 image build

---

Dockerfile
Makefile

Moves the ARCH build argument after the first FROM so it has the proper
value.
(https://docs.docker.com/engine/reference/builder/#understand-how-arg-and-from-interact)
Adds the GOARM=7 option to the armv7 GO build.
/kind bug
Fixes #239 
```release-note
NONE
```

fix: armv7 docker builds

---

.github/workflows/darwin.yaml
.github/workflows/linux.yaml
.github/workflows/windows.yaml

Prior to this patch, the Go version for the Windows tests in Github
resolved to [`1.15.15`][1].
With this patch, the Go version for the Windows tests is fixed to
actually resolve to the latest version (^1.16), consistent to the other
platforms.
This patch also bumps [`actions/setup-go`][2] to the latest version,
consistent with the other platforms.
Lastly, in order to rapidly debug test issues, issue `go version` prior to
running any test.
[1]: https://github.com/kubernetes-csi/csi-driver-nfs/runs/4211323920?check_suite_focus=true
[2]: https://github.com/actions/setup-go
```release-note
none
```

Windows go version

---

Dockerfile

/kind feature
fix: mount.nfs: Protocol not supported on NFSv3
Fixes #251
cc @strideynet
```release-note
fix: mount.nfs: Protocol not supported on NFSv3
```

fix: mount.nfs: Protocol not supported on NFSv3

---

cmd/nfsplugin/main.go
hack/release-image.sh
pkg/nfs/controllerserver_test.go
pkg/nfs/nfs.go
pkg/nfs/nfs_test.go
test/e2e/e2e_suite_test.go

/kind bug
fix: driver version print in logging
```console
DRIVER INFORMATION:
-------------------
Build Date: "2021-12-07T07:40:50Z"
Compiler: gc
Driver Name: nfs.csi.k8s.io
Driver Version: v3.1.0
Git Commit: 9ab192ba31631ea1baac813ef96005e78a38d6fe
Go Version: go1.16
Platform: linux/amd64
Streaming logs below:
I1207 07:43:02.286214   26063 server.go:117] Listening for connections on address: &net.UnixAddr{Name:"/tmp/csi.sock", Net:"unix"}
```
Fixes #
```release-note
fix: driver version print in logging
```

fix: driver version print in logging

---

pkg/nfs/controllerserver.go
pkg/nfs/controllerserver_test.go

/kind feature
feat: change volume id format
use separator `#` instead of `/`, original separator(`/`) makes it difficult to parse share and subdir
Fixes #
```release-note
feat: change volume id format
```

feat: change volume id format

---

Dockerfile

```
+----------+------------------+----------+-------------------+------------------+--------------------------------------+
| LIBRARY  | VULNERABILITY ID | SEVERITY | INSTALLED VERSION |  FIXED VERSION   |                TITLE                 |
+----------+------------------+----------+-------------------+------------------+--------------------------------------+
| bsdutils | CVE-2021-3995    | MEDIUM   | 2.36.1-8          | 2.36.1-8+deb11u1 | util-linux: Unauthorized unmount     |
|          |                  |          |                   |                  | of FUSE filesystems belonging        |
|          |                  |          |                   |                  | to users with similar uid...         |
|          |                  |          |                   | …
```

update base image version of plugin binary to fix CVEs

---

deploy/example/storageclass-nfs.yaml

doc: remove mount-options in example
Fixes #274
```release-note
none
```

doc: comment mount-options in example

---

Makefile

/kind feature
feat: add ppc64le arch support
Fixes #288
```release-note
feat: add ppc64le arch support
```

feat: add ppc64le arch support

---

docs/driver-parameters.md
pkg/nfs/controllerserver.go
pkg/nfs/controllerserver_test.go
pkg/nfs/nfs.go
pkg/nfs/nodeserver.go
pkg/nfs/nodeserver_test.go
test/e2e/e2e_suite_test.go

/kind feature
feat: add mountPermissions parameter in storage class
user could set customized mountPermissions in storage class, e.g.
```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
name: nfs-csi
provisioner: nfs.csi.k8s.io
parameters:
server: nfs-server.default.svc.cluster.local
share: /
mountPermissions: "0755"
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
- hard
- nfsvers=4.1
```
Fixes #
```release-note
feat: add mountPermissions parameter in storage class
```

feat: add mountPermissions parameter in storage class

---

Dockerfile

trying to fix following image push error:
https://storage.googleapis.com/kubernetes-jenkins/logs/post-csi-driver-nfs-push-images/1505022117538697216/build-log.txt
```
Dockerfile:21
--------------------
19 |     
20 |     # Copy nfsplugin from build _output directory
21 | >>> COPY bin/${ARCH}/nfsplugin /nfsplugin
22 |     
23 |     RUN apt update && apt-mark unhold libcap2
--------------------
error: failed to solve: failed to compute cache key: failed to calculate checksum of ref iiep4siygqcc5hgky6t6fme3l::ghhr8b16cjp4zwohx9ri9j1p1: "/bin/amd64/nfsplugin": not found
+ docker buildx rm multiarchimage-buildertest
make: *** [release-tools/build.make:149: push-multiarch-nfsplugin] Error 1
ERROR
ERROR: …
```

chore: fix pushing image pipeline broken

---

Dockerfile

fix: post-csi-driver-nfs-push-images failure
Fixes #296
```release-note
none
```

fix: post-csi-driver-nfs-push-images failure

---

go.mod
go.sum
vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client.go
vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go
vendor/github.com/prometheus/client_golang/prometheus/promhttp/option.go
vendor/modules.txt

Upgrade the Prometheus client to v1.11.1.
This commit is the result of running:
```
go get github.com/prometheus/client_golang@v1.11.1 \
&& go mod tidy && go mod vendor
```
See https://github.com/prometheus/client_golang/security/advisories/GHSA-cg3q-j54f-5p7p
Upgrades `github.com/prometheus/client_golang` to v1.11.1, where the vulnerability has been fixed.
Fixes #300
One handy way to check that the version of `client_go` used for compiling contains the security patch, is to run go mod vendor and check that the `InstrumentRoundTripperCounter` method [contains a variadic `options` argument](https://github.com/prometheus/client_golang/compare/v1.11.0...v1.11.1#diff-7871a83741d29b5f2 …

Address CVE-2022-21698

---

Dockerfile

/kind bug
fix: CVE issues in image build
Fixes #
```
+-------------+------------------+----------+-------------------+-----------------+---------------------------------------+
|   LIBRARY   | VULNERABILITY ID | SEVERITY | INSTALLED VERSION |  FIXED VERSION  |                 TITLE                 |
+-------------+------------------+----------+-------------------+-----------------+---------------------------------------+
| libc-bin    | CVE-2021-33574   | CRITICAL | 2.31-13+deb11u2   | 2.31-13+deb11u3 | glibc: mq_notify does                 |
|             |                  |          |                   |                 | not handle separately …
```

fix: CVE issues in image build

---

pkg/nfs/controllerserver.go
pkg/nfs/controllerserver_test.go
pkg/nfs/nfs.go
pkg/nfs/nfs_test.go
test/external-e2e/run.sh
test/external-e2e/testdriver.yaml

/kind bug
fix: disallow block volume capability
should return error for block volume capability
Fixes #
```
fix: disallow block volume capability
```

fix: disallow block volume capability

---

docs/csi-dev.md

doc: align the endpoint with environment variable used below to avoid confusing
Fixes #
```release-note
none
```

doc: align the endpoint with environment variable used below to avoid confusing

---

pkg/nfs/nodeserver.go
pkg/nfs/nodeserver_test.go

/kind bug
In case the NodeUnpublishVolume procedured was aborted after unmounting
the volume, a repeated call will return an error like "Volume not
mounted".
Instead of returning the error, log a message and return success to
indicate that the volume is not mounted anymore.
```release-note
NONE
```

fix: NodeUnpublishVolume should be idempotent

---

pkg/nfs/nodeserver.go
pkg/nfs/nodeserver_test.go

/kind bug
fix: use mount.CleanupMountPoint in NodeUnpublishVolume which is better for handling stale nfs connections during unmount process
// CleanupMountPoint unmounts the given path and deletes the remaining directory
// if successful. If extensiveMountPointCheck is true IsNotMountPoint will be
// called instead of IsLikelyNotMountPoint. IsNotMountPoint is more expensive
// but properly handles bind mounts within the same fs.
Fixes #
```release-note
fix: use mount.CleanupMountPoint in NodeUnpublishVolume for handling stale nfs connections during unmount process
```

fix: use mount.CleanupMountPoint in NodeUnpublishVolume for handling stale nfs connections during unmount process

---

docs/driver-parameters.md
pkg/nfs/nodeserver.go
pkg/nfs/nodeserver_test.go
test/e2e/dynamic_provisioning_test.go
test/e2e/e2e_suite_test.go

/kind feature
feat: skip chmod if mountPermissions is 0 after mount
Fixes #327
```release-note
feat: skip chmod if mountPermissions is 0 after mount
```

feat: skip chmod if mountPermissions is 0 after mount

---

pkg/nfs/nodeserver.go

/kind bug
fix: bypass chmod if mounting point permissions are correct
Fixes #337
```release-note
fix: bypass chmod if mounting point permissions are correct
```

fix: bypass chmod if mounting point permissions are correct

---

go.mod
pkg/nfs/nodeserver.go
pkg/nfs/utils.go
pkg/nfs/utils_test.go
vendor/modules.txt

/kind feature
feat: support IPv6 server address
similar fix to https://github.com/kubernetes/kubernetes/pull/101067
Fixes #
```release-note
feat: support IPv6 server address
```

feat: support IPv6 server address

---

charts/README.md

>
> /kind bug
> /kind design
> /kind flake
**What this PR does / why we need it**: 
Enhance documentation pointing out support for extra labels to k8s resources deployed by chart.

docs: add customLabels parameter to chart README

---

deploy/csi-nfs-driverinfo.yaml
pkg/nfs/controllerserver.go
pkg/nfs/fake_mounter.go

/kind feature
feat: disable inline volume by default in kubectl install
Fixes #364
```release-note
feat: disable inline volume by default in kubectl install
```

feat: disable inline volume by default in kubectl install

---

deploy/example/README.md
deploy/example/pv-nfs-csi.yaml
deploy/example/storageclass-nfs.yaml

doc: remove nconnect mount option, `nconnect=8` mount option would lead to nfs list directory failure (cause inconsistent list result due to multi threads)
Fixes #
```
none
```

doc: remove nconnect mount option

---

.github/workflows/trivy.yaml
Makefile
hack/boilerplate/boilerplate.py
test/external-e2e/run.sh

fix: buildx issue with provenance disabled
Fixes #
```
none
```

fix: buildx issue with provenance disabled

---

pkg/nfs/controllerserver.go

>
/kind bug
> /kind design
> /kind flake
It creates also parent directories of sub-directories under the mounted base-dir. Just like `mkdir -p` does.
Fixes #411
```release-note
none
```

fix: use `mkdir -p` for creating subdir in mounted base-dir

---

deploy/example/pvc-volume-clone.yaml
pkg/nfs/controllerserver.go
pkg/nfs/controllerserver_test.go
pkg/nfs/nfs.go
test/external-e2e/testdriver.yaml

/kind feature
This PR introduces a first step towards supporting snapshots - volume cloning from other volumes. It's implemented as outlined in https://github.com/kubernetes-csi/csi-driver-nfs/issues/30#issuecomment-617496994, and it is just an invocation of `cp -a [src]/. [dst]` to recursively copy the content of the source volume to the destination volume and adequately treat soft and hard links.
I would like to first get a consensus on the design decisions and then I can follow up with snapshots and volume copy from snapshots.
first step towards implementing https://github.com/kubernetes-csi/csi-driver-nfs/issues/31
**Does this PR introduce a …

feat: volume clone from source volume

---

deploy/example/statefulset.yaml

>
> /kind bug
> /kind design
> /kind flake
/kind cleanup
The volume.beta.kubernetes.io/storage-class annotation is deprecated since v1.9.
Changed it to a new way to deal with some e2e issues.
Fixes #
```release-note
none
```

test(e2e): change the storageclass configuration method in the test file

---

test/external-e2e/run.sh

/kind cleanup
The `storage.googleapis.com/kubernetes-release` URL is a hard coded path to a GCS bucket location. To allow redirecting and spreading the load across multiple hosting locations, the `dl.k8s.io` URL has been introduced.
Related PRs:
- https://github.com/kubernetes-sigs/image-builder/pull/656
- https://github.com/kubernetes-sigs/cluster-api/pull/4958
None
```release-note
none
```

Use dl.k8s.io instead of hardcoded GCS URIs

---

pkg/nfs/controllerserver.go
pkg/nfs/controllerserver_test.go

/kind bug
When using the `share` parameter on either `StorageClass` or `SnapshotVolumeClass`, the path to snapshots would contain the `share` parameter twice, e.g.
```
/mnt/nfs/mnt/nfs/snapshot-id/src-pvc-id.tar.gz   # duplicate
/mnt/nfs/snapshot-id/src-pvc-id.tar.gz           # desired
```
This PR ensures it's the desired path.
Fixes https://github.com/kubernetes-csi/csi-driver-nfs/issues/459
Should I also introduce some special treatment regarding the old broken snapshot paths? For those who already have created some snapshots and they are stored in the broken path.
```release-note
bugfix: correct …
```

bugfix: correct snapshot path when using share parameter

---

pkg/nfs/controllerserver.go

/kind bug
chore: forbid invalid parameters in snapshot storage class
Fixes #
```release-note
none
```

chore: forbid invalid parameters in snapshot storage class

---

release-tools/SIDECAR_RELEASE_PROCESS.md
release-tools/build.make
release-tools/cloudbuild.yaml
release-tools/contrib/get_supported_version_csi-sidecar.py
release-tools/prow.sh

/kind cleanup
chore: update release-tools
Fixes #
```release-note
none
```

chore: update release-tools

---

cmd/nfsplugin/main.go

/kind bug
golang 1.21 introduced a fix to flag: https://github.com/golang/go/commit/00401835c1d5122a84f0500e48655cd787402f3f, which makes the `Set` fail loudly (panic) if it happened before the definition. Before go1.21 it just fails silently.
Fixes #
```release-note
fix: flag panic if a flag is defined after being set
```

fix: flag panic if a flag is defined after being set

---

go.mod
vendor/modules.txt

Fix `go list -mod=readonly -m all` by adding a replace for `k8s.io/dynamic-resource-allocation` that points to the Kubernetes version currently in use.
The packages is not used here, but making the dependency resolvable makes the go toolchain happy.
cf.: https://github.com/kubernetes/kubernetes/blob/4b48ab1fdbdeee3568790e44bea55ea719205025/go.mod#L265
```release-note
none
```

go.mod: Fix unresolvable indirect dependency

---

.github/workflows/static.yaml
.golangci.yml
pkg/nfs/controllerserver.go
pkg/nfs/controllerserver_test.go
pkg/nfs/fake_mounter.go
pkg/nfs/identityserver.go
pkg/nfs/nodeserver.go
pkg/nfs/utils.go
test/e2e/driver/nfs_driver.go
test/e2e/testsuites/dynamically_provisioned_inline_volume.go
test/e2e/testsuites/specs.go

>
> /kind bug
> /kind design
> /kind flake
/kind test
test: upgrade golangci/golangci-lint-action to v1.54
Fixes #
```release-note
none
```

test: upgrade golangci/golangci-lint-action to v1.54

---

deploy/example/deployment.yaml
deploy/example/nfs-provisioner/nginx-pod.yaml
deploy/example/nginx-pod-inline-volume.yaml
deploy/example/pv-nfs-csi.yaml
deploy/example/statefulset.yaml

doc: fix readOnly setting doc
- following csi.readOnly is not supported in CSI driver
```
csi:
driver: driver-name
readOnly: false
```
Fixes #
```
none
```

doc: fix readOnly setting doc

---

README.md
deploy/example/cloning/README.md
deploy/example/cloning/nginx-pod-restored-cloning.yaml
deploy/example/cloning/pvc-nfs-cloning.yaml
deploy/example/nginx-pod-nfs.yaml
hack/verify-yamllint.sh

>
> /kind bug
> /kind design
> /kind flake
doc: add volume cloning doc
Fixes #
```release-note
none
```

doc: add volume cloning doc

---

release-tools/KUBERNETES_CSI_OWNERS_ALIASES
release-tools/SIDECAR_RELEASE_PROCESS.md
release-tools/go-modules-update.sh
release-tools/prow.sh

chore: Update release tools
```
git checkout -b update_release-tools4
git subtree pull --squash --prefix=release-tools https://github.com/kubernetes-csi/csi-release-tools.git master
git push origin update_release-tools4
```
Fixes #
```
none
```

chore: Update release tools

---

pkg/nfs/nodeserver.go
pkg/nfs/nodeserver_test.go
pkg/nfs/utils.go

/kind bug
fix: add locks for nodeserver publish/unpublish operations
Per CSI(Container Storage Interface), if a mount operation is in-progress for the volume then CSI driver should return error code "10 ABORTED"
Fixes #569 #209
```release-note
fix: add locks for nodeserver publish/unpublish operations
```

fix: add locks for nodeserver publish/unpublish operations

---

pkg/nfs/nodeserver.go

/kind bug
fix: NodeGetVolumeStats crash
Fixes #
```release-note
fix: NodeGetVolumeStats crash
```

fix: NodeGetVolumeStats crash

---

pkg/nfs/controllerserver.go

/kind cleanup
cleanup: remove unnecessary getArchivedInternalVolumePath func
Fixes #
```release-note
none
```

cleanup: remove unnecessary getArchivedInternalVolumePath func

---

pkg/nfs/controllerserver.go
test/e2e/dynamic_provisioning_test.go
test/e2e/e2e_suite_test.go

/kind bug
fix: delete volume failure in archive mode when subDir contains /
Fixes #595
```release-note
fix: delete volume failure in archive mode when subDir contains /
```

fix: delete volume failure in archive mode when subDir contains /

---

pkg/nfs/controllerserver.go

/kind bug
fix: remove stale archived volume copy before rename
The user might put non-unique spec for subdir:
```
subDir: ${pvc.metadata.namespace}/${pvc.metadata.name}
```
Then, `os.Rename(internalVolumePath, archivedInternalVolumePath)` can fail becaue the destination (`archivedInternalVolumePath`) already exists. It's safer to remove it before `os.Rename()`.
Fixes #
```release-note
fix: remove stale archived volume copy before rename
```

fix: remove stale archived volume copy before rename

---

deploy/example/snapshot/README.md

>
> /kind bug
> /kind design
> /kind flake
Fixes broken links referencing old GitHub organization name.
Fixes #
```release-note
none
```

Fix org name in links to snapshot resources

---

pkg/nfs/controllerserver.go

/kind bug
fix: archive dir error
from below error msg, `os.Rename` is not a sync call, unmount will be called before os.Rename is complete, therefore the os.Rename would fail finally, this PR adds a 2s second before unmount to make sure os.Rename could be completed
```
[pod/csi-nfs-controller-76c9866697-gbwgk/nfs] I0807 01:47:25.770987       1 utils.go:109] GRPC call: /csi.v1.Controller/DeleteVolume
[pod/csi-nfs-controller-76c9866697-gbwgk/nfs] I0807 01:47:25.771001       1 utils.go:110] GRPC request: {"secrets":"***stripped***","volume_id":"nfs-server.default.svc.cluster.local##pvc-0ad8fba9-dcb2-4106-8887-c4968eb3afd6##archive"}
[pod/csi-nfs-controller-76c9866697-gbwgk/nfs] I0807 01:47:25.771043       1 …
```

fix: archive dir error

---

pkg/nfs/controllerserver.go
pkg/nfs/utils.go
pkg/nfs/utils_test.go

/kind bug
fix: archive dir error#2
refix: https://github.com/kubernetes-csi/csi-driver-nfs/pull/729
Fixes #
```release-note
fix: archive dir error
```

fix: archive dir error#2

---

pkg/nfs/controllerserver.go
pkg/nfs/nfs.go

/kind bug
fix: delete volume error in archive deletion mode
when onDelete: archive, there could be delete volume error with error msg rename xxx: no such file or directory since there is a bug in csi-provisioner that DeleteVolume may be performed twice, this PR adds a 1 min cache and lock to workaround this issue.
Fixes #
```release-note
fix: delete volume error in archive deletion mode
```

fix: delete volume error in archive deletion mode

---

deploy/example/snapshot/README.md

>
> /kind bug
> /kind design
> /kind flake
Updates README.md to note external-snapshotter is required along with explaining how the snapshots are created. This fixes the issue I was having of snapshots not being created even though I followed the volumesnapshot example.
Fixes #
```release-note
none
```

 …Update README.md to note external-snapshotter is required

---

.github/workflows/static.yaml
pkg/nfs/controllerserver.go
pkg/nfs/nfs.go
pkg/nfs/nfs_test.go
pkg/nfs/nodeserver.go
pkg/nfs/nodeserver_test.go
pkg/nfs/server.go
test/e2e/dynamic_provisioning_test.go
test/utils/testutil/testutil.go

/kind cleanup
>
> /kind bug
> /kind design
> /kind flake
chore: upgrade golint version
Fixes #
```release-note
none
```

chore: upgrade golint version

---

pkg/nfs/controllerserver.go
pkg/nfs/utils.go
pkg/nfs/utils_test.go
test/e2e/e2e_suite_test.go

/kind bug
fix: remove parent dir in DeleteVolume
Fixes #763
<details>
```
[pod/csi-nfs-controller-67c56ff89f-j244d/nfs] I0915 05:01:30.363893       1 utils.go:110] GRPC call: /csi.v1.Controller/DeleteVolume
[pod/csi-nfs-controller-67c56ff89f-j244d/nfs] I0915 05:01:30.364289       1 utils.go:111] GRPC request: {"secrets":"***stripped***","volume_id":"nfs-server.default.svc.cluster.local##nfs-7869/pvc-m74ps#pvc-f2772f7e-a91c-4b0e-83d5-9cb0b3da9998#"}
[pod/csi-nfs-controller-67c56ff89f-j244d/nfs] I0915 05:01:30.364360       1 controllerserver.go:225] DeleteVolume: found mountOptions(nfsvers=4.1) for …
```

fix: remove parent dir in DeleteVolume

---

docs/csi-debug.md

the getting pod description command is missing keyword 'pod' 
Fixes #
```release-note
none
```

doc: missing keyword pod in command

---

release-tools/cloudbuild.yaml
release-tools/prow.sh

/kind cleanup
chore: Update csi release tools
```
git subtree pull --squash --prefix=release-tools https://github.com/kubernetes-csi/csi-release-tools.git master
```
Fixes #
```
none
```

chore: Update csi release tools 

---

pkg/nfs/controllerserver.go
pkg/nfs/utils.go
pkg/nfs/utils_test.go

/kind bug
fix: only cleanup empty parent directories during DeleteVolume
<details>
```
[pod/csi-nfs-controller-6dcc8cc68c-mn26w/nfs] I0313 10:33:11.629160       1 utils.go:111] GRPC call: /csi.v1.Controller/DeleteVolume
[pod/csi-nfs-controller-6dcc8cc68c-mn26w/nfs] I0313 10:33:11.629419       1 utils.go:112] GRPC request: {"secrets":"***stripped***","volume_id":"nfs-server.default.svc.cluster.local##nfs-270/pvc-dxb27#pvc-ce9651cb-815e-463c-bd67-a7215b97b85c#"}
[pod/csi-nfs-controller-6dcc8cc68c-mn26w/nfs] I0313 10:33:11.630434       1 controllerserver.go:226] DeleteVolume: found mountOptions(nfsvers=4.1) for volume(nfs-server.default.svc.cluster.local##nfs-270/pvc-dxb27#pvc-ce9651cb-815e-463c-bd67-a7215b97b85c#) …
```

fix: only cleanup empty parent directories during DeleteVolume

---

docs/driver-parameters.md
pkg/nfs/controllerserver.go
pkg/nfs/controllerserver_test.go

/kind feature
feat: support mountOptions parameter in VolumeSnapshotClass
Fixes #861
```release-note
feat: support mountOptions parameter in VolumeSnapshotClass
```

feat: support mountOptions parameter in VolumeSnapshotClass

---

pkg/nfs/controllerserver.go
pkg/nfs/utils.go
pkg/nfs/utils_test.go

/kind bug
fix: create voume/snapshot should respect mountOptions in secret, thus user could only set mountOptions in secret for both create and delete volume/snapshot
Fixes #
```release-note
fix: create voume/snapshot should respect mountOptions in secret
```

chore: create voume/snapshot should respect mountOptions in secret

---

charts/README.md

Fixes #968
```release-note
none
```

doc: update semver change doc for helm chart install
