.prow.sh

Adds .prow.sh config to enable prow jobs
Fixes #
```release-note
NONE
```

Add .prow.sh to enable prow jobs

---

pkg/nfs/nfs.go

/kind bug
By supporting MULTI_NODE_MULTI_WRITER, we inherently support all the other access modes.  Also store supported access modes as a map to make it easier to lookup.
Fixes #
```release-note
Adds support all access modes.
```

Add more access modes to volume capabilities

---

CHANGELOG/CHANGELOG-2.0.md

Generate changelog for 2.0.0 release
Fixes #
```release-note
NONE
```

Add 2.0 changelog

---

OWNERS

will find an intern working on this project to make this project move faster, some ideas:
1. add e2e tests
2. add more functionalities to this driver
refer to https://github.com/kubernetes-csi/csi-driver-smb
Fixes #
```release-note
none
```
/assign @msau42

doc: add as approver

---

examples/kubernetes/nfs-provisioner/nfs-server-lb.yaml
examples/kubernetes/nfs-provisioner/nfs-server.yaml

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```

fix: broken manifest for `nfs-server.yaml`

---

.github/workflows/sanity.yaml

Following https://github.com/kubernetes-csi/csi-driver-nfs/pull/53#issuecomment-707422392 , this PR adds a Github Action for sanity tests
Fixes #
```release-note
None
```

CI: Add GH Actions for sanity tests

---

.cloudbuild.sh
cloudbuild.yaml

>
> /kind bug
> /kind design
> /kind flake
add the required artifacts to run `post-csi-driver-nfs-push-images`
Fixes #65
```release-note
None
```

Add symlink for cloudbuild.yaml and .cloudbuild.sh

---

.github/workflows/darwin.yaml

Add GH Actions workflow for running unit tests on darwin
Fixes #
```release-note
None
```

CI: add GH Actions workflow for Darwin unit tests

---

test/sanity/run-test.sh

/kind flake
test: add `ControllerGetCapabilities` and `ValidateVolumeCapabilities in sanity test
Fixes #
```release-note
None
```

test: add `ControllerGetCapabilities` and `ValidateVolumeCapabilities in sanity test

---

charts/csi-driver-nfs/.helmignore
charts/csi-driver-nfs/Chart.yaml
charts/csi-driver-nfs/templates/NOTES.txt
charts/csi-driver-nfs/templates/_helpers.tpl
charts/csi-driver-nfs/templates/csi-nfs-controller.yaml
charts/csi-driver-nfs/templates/csi-nfs-driverinfo.yaml
charts/csi-driver-nfs/templates/csi-nfs-node.yaml
charts/csi-driver-nfs/templates/rbac-csi-nfs-controller.yaml
charts/csi-driver-nfs/values.yaml

Add Helm chart for CSI NFS driver
Fixes #
```release-note
None
```

Add Helm chart for CSI NFS driver

---

README.md
deploy/kubernetes/install-driver.sh
deploy/kubernetes/uninstall-driver.sh
docs/install-csi-driver.md

>
> /kind bug
> /kind design
> /kind flake
Add instructions to install the driver.
Depend on this PR: https://github.com/kubernetes-csi/csi-driver-nfs/pull/80
Fixes #
```release-note
None
```

doc: add install instructions

---

deploy/csi-nfs-controller.yaml
deploy/csi-nfs-node.yaml
deploy/install-driver.sh

doc: use quay images
Fixes #
```release-note
none
```

doc: use quay images

---

Makefile

>
> /kind bug
> /kind design
> /kind flake
Include `build.make` in Makefile for cloud build
Fixes #
```release-note
None
```

Include `build.make` in Makefile for cloud build

---

test/integration/run-test.sh

>
> /kind bug
> /kind design
> /kind flake
Change the way to install CSC to avoid integration test failures.
Fixes #
```release-note
None
```

fix: change the way to install CSC to fix integration test

---

go.mod
pkg/mounter/safe_mounter_unix.go
pkg/nfs/fake_mounter.go
pkg/nfs/identityserver_test.go
pkg/nfs/indentityserver.go
pkg/nfs/nfs_test.go
pkg/nfs/nodeserver.go
pkg/nfs/nodeserver_test.go
test/utils/testutil/testutil.go

>
> /kind bug
> /kind design
> /kind flake
Add unit tests for identityserver.go
Fixes #
```release-note
None
```

test: Add unit tests for identityserver and nodeserver

---

Makefile
hack/release-image.sh

/kind bug
Fixes #
fix: release-image.sh script
```release-note
none
```

fix: release-image.sh script

---

test/sanity/run-test.sh

/kind test
test: upgrade sanity-test to v4.0.2
Fixes #
```release-note
none
```

test: upgrade sanity-test to v4.0.2

---

.github/workflows/ubuntu.yaml
hack/verify-all.sh

/kind cleanup
test: add unit test action on Ubuntu
Fixes #
```release-note
none
```

test: add unit test action on Ubuntu

---

.github/workflows/darwin.yaml
.github/workflows/ubuntu.yaml

/kind cleanup
test: enable GH actions on all branches
Fixes #
```release-note
none
```

test: enable GH actions on all branches

---

Makefile
deploy/example/deployment.yaml
hack/verify-examples.sh
test/e2e/e2e_suite_test.go

/kind cleanup
test: refactor verify example test
Fixes #
```release-note
none
```

test: refactor verify example test

---

pkg/nfs/nodeserver.go

/kind cleanup
cleanup: disable NodeStageVolume
Fixes #142
```release-note
none
```
/assign @gnufied

cleanup: disable NodeStageVolume

---

charts/index.yaml
hack/verify-all.sh
hack/verify-helm-chart-files.sh
hack/verify-helm-chart.sh

/kind bug
test: add verify-helm-chart-files.sh script
Fixes #
```release-note
none
```

test: add verify-helm-chart-files.sh script

---

README.md

>
> /kind bug
> /kind design
> /kind flake
Update k8s support version
Fixes #
```release-note
none
```

doc: update supported k8s version

---

release-tools/build.make

/kind feature
Update release tools
Fixes #
```release-note
none
```

Update release tools

---

Dockerfile

/kind feature
feat: add ARCH in Dockerfile
Fixes #
```release-note
none
```

feat: add ARCH in Dockerfile

---

pkg/nfs/nodeserver.go
pkg/nfs/nodeserver_test.go
pkg/nfs/utils.go

/kind bug
Fixes #200
```release-note
fix: remove unnecessary lock
```

fix: remove unnecessary lock

---

test/external-e2e/run.sh
test/external-e2e/testdriver.yaml

/kind cleanup
test: run external e2e test using 1.20 suites
Fixes #
```release-note
none
```

test: run external e2e test using 1.20 suites

---

deploy/example/storageclass-nfs.yaml
test/external-e2e/run.sh

/kind test
test: run externel tests with 1.21 suites
Fixes #
```release-note
none
```

test: run externel tests with 1.21 suites

---

deploy/example/daemonset-nfs-ephemeral.yaml
hack/verify-examples.sh
test/external-e2e/run.sh

doc: add daemonset-nfs-ephemeral.yaml example
Fixes #
```release-note
none
```

doc: add daemonset-nfs-ephemeral.yaml example

---

charts/README.md

Update README.md
```release-note
NONE
```

master: update release-tools

---

README.md

kind cleanup
Spelling is a quality issue
None
Fixes #
```release-note
none
```

cluster misspelled

---

Makefile

/kind feature
feat: support armv7 image build
Fixes #
```release-note
feat: support armv7 image build
```

feat: support armv7 image build

---

.github/workflows/trivy.yaml
Dockerfile
Makefile

/kind bug
fix: vulnerability issue in docker image
This PR upgrades Dockerfile base image to fix vulnerability issue in docker image, and also adds trivy vulnerability scanning test 
Fixes #
```release-note
fix: vulnerability issue in docker image
```

fix: vulnerability issue in docker image

---

deploy/example/README.md
deploy/example/nfs-provisioner/README.md

fix links of 'install-csi-driver' in example docs.

doc: fix links of docs

---

deploy/example/storageclass-nfs.yaml
docs/driver-parameters.md

doc: update mountOptions for DeleteVolume doc
Fixes #
```release-note
none
```

doc: update mountOptions for DeleteVolume doc

---

.github/workflows/static.yaml
pkg/nfs/controllerserver.go
pkg/nfs/controllerserver_test.go

/kind bug
fix: ValidateVolumeCapabilities
Fixes #
```release-note
fix: ValidateVolumeCapabilities
```

fix: ValidateVolumeCapabilities

---

Dockerfile

/kind cleanup
cleanup: remove unnecessary CVE packages
Fixes #
```release-note
none
```

cleanup: remove unnecessary CVE packages

---

.github/workflows/codespell.yml
.github/workflows/shellcheck.yaml
.prow.sh
docs/csi-debug.md
test/e2e/testsuites/dynamically_provisioned_reclaim_policy_tester.go
test/e2e/testsuites/testsuites.go
test/integration/run-test.sh
test/sanity/run-test.sh
test/utils/check_driver_pods_restart.sh
test/utils/nfs_log.sh

test: add codespell shellcheck github actions
Fixes #
```release-note
none
```

test: add codespell shellcheck github actions

---

Dockerfile

/kind bug
fix: CVE-2022-0778 in image build
Fixes #
```release-note
none
```

fix: CVE-2022-0778 in image build

---

deploy/example/pv-nfs-csi.yaml
deploy/example/storageclass-nfs.yaml
test/e2e/dynamic_provisioning_test.go

doc: add nconnect mount option in nfs example
Fixes #
```release-note
none
```

doc: add nconnect mount option in nfs example

---

Dockerfile

/kind bug
fix: CVE issues in image build on release-3.1
Fixes #
```release-note
fix: CVE issues in image build on release-3.1
```

fix: CVE issues in image build on release-3.1

---

Dockerfile

/kind bug
fix: CVE issues in image build on release-3.0
Fixes #
```release-note
fix: CVE issues in image build on release-3.0
```

fix: CVE issues in image build on release-3.0

---

.github/workflows/codeql-analysis.yml
Dockerfile

/kind bug
fix: CVE-2018-25032 in image build
Fixes #
```release-note
fix: CVE-2018-25032 in image build
```

fix: CVE-2018-25032 in image build

---

deploy/example/README.md
deploy/example/pv-nfs-csi.yaml
deploy/example/pvc-nfs-csi-static.yaml
deploy/example/storageclass-nfs.yaml

doc: refine PV doc
Fixes #
```release-note
none
```

doc: refine PV doc

---

hack/verify-all.sh

test: fix golint error
Fixes #
```release-note
none
```

test: fix golint error

---

Dockerfile

/kind bug
fix: CVE-2022-1271 in image build
```
+----------+------------------+----------+-------------------+-------------------+--------------------------------------+
| LIBRARY  | VULNERABILITY ID | SEVERITY | INSTALLED VERSION |   FIXED VERSION   |                TITLE                 |
+----------+------------------+----------+-------------------+-------------------+--------------------------------------+
| gzip     | CVE-2022-1271    | HIGH     | 1.10-4            | 1.10-4+deb11u1    | gzip: arbitrary-file-write           |
|          |                  |          |                   |                   | vulnerability                        |
|          |                  |          |                   | …
```

fix: CVE-2022-1271 in image build

---

pkg/nfs/nodeserver.go

/kind cleanup
cleanup: refine mount logging
Fixes #
```release-note
none
```

cleanup: refine mount logging

---

deploy/example/README.md
deploy/example/nfs-provisioner/nginx-pod.yaml
deploy/example/pv-nfs-csi.yaml
deploy/example/storageclass-nfs.yaml
docs/driver-parameters.md

chore: remove hard mount option
per https://github.com/kubernetes-csi/csi-driver-nfs/issues/260#issuecomment-1123274561
Fixes #
```release-note
none
```

chore: remove hard mount option

---

pkg/nfs/nodeserver.go
pkg/nfs/utils.go
pkg/nfs/utils_test.go

/kind cleanup
chore: refine bypass chmod code
Fixes #
```release-note
none
```

chore: refine bypass chmod code

---

docs/driver-parameters.md
pkg/nfs/controllerserver.go
pkg/nfs/controllerserver_test.go
pkg/nfs/nfs.go
pkg/nfs/nodeserver.go
pkg/nfs/utils.go
pkg/nfs/utils_test.go
test/e2e/dynamic_provisioning_test.go
test/e2e/e2e_suite_test.go

/kind feature
feat: add subDir in storage class parameters
Fixes #
```release-note
feat: add subDir in storage class parameters
```

feat: add subDir in storage class parameters

---

.github/workflows/codespell.yml
.github/workflows/trivy.yaml
pkg/nfs/utils_test.go

chore: fix code spelling issue
Fixes #
```release-note
none
```

chore: fix code spelling issue

---

CONTRIBUTING.md

Signed-off-by: amolmote <amolmote201@gmail.com>
Fixes #376

Fixes broken link

---

release-tools/prow.sh

update release-tools to latest

---

hack/verify-all.sh
hack/verify-helm-chart-index.sh

>
> /kind bug
> /kind design
> /kind flake
/kind feature
test: add helm repo install check
Fixes #
```release-note
none
```

test: add helm repo install check

---

go.mod
go.sum
vendor/golang.org/x/net/html/token.go
vendor/golang.org/x/net/http2/frame.go
vendor/golang.org/x/net/http2/hpack/hpack.go
vendor/golang.org/x/net/http2/server.go
vendor/modules.txt

/kind bug
fix: CVE-2022-41723
Fixes #
```release-note
fix: CVE-2022-41723
```

fix: CVE-2022-41723

---

Dockerfile

/kind cleanup
Update the debian base image to the latest release.
None
None
```release-note
None
```

Update debian-base image to v1.4.3

---

release-tools/prow.sh

/kind cleanup
chore: update csi-release-tools
Fixes #
```
none
```

chore: update csi-release-tools

---

charts/README.md

doc: fix doc typo
Fixes #514
```release-note
none
```

doc: fix doc typo

---

hack/verify-gomod.sh

/kind cleanup
test: add more gomod check
Fixes #
```release-note
none
```

test: add more gomod check

---

Dockerfile

/kind feature
feat: switch to bookworm debian base image
bookworm debian base image has fewer CVEs compared to bulleye debian base image
```
==============================================
Total: 97 (UNKNOWN: 0, LOW: 72, MEDIUM: 14, HIGH: 10, CRITICAL: 1)
==============================================
Total: 210 (UNKNOWN: 0, LOW: 104, MEDIUM: 47, HIGH: 50, CRITICAL: 9)
```
Fixes #
```release-note
feat: switch to bookworm debian base image
```

feat: switch to bookworm debian base image

---

release-tools/SIDECAR_RELEASE_PROCESS.md
release-tools/generate_patch_release_notes.sh
release-tools/prow.sh
release-tools/pull-test.sh

/kind cleanup
Update release tools2
```console
git checkout -b update_release-tools2
git subtree pull --squash --prefix=release-tools https://github.com/kubernetes-csi/csi-release-tools.git master
git push origin update_release-tools2
```
Fixes #
```
none
```

[chore] Update release tools2

---

go.mod
go.sum
vendor/golang.org/x/crypto/ssh/channel.go
vendor/golang.org/x/crypto/ssh/client.go
vendor/golang.org/x/crypto/ssh/handshake.go
vendor/golang.org/x/crypto/ssh/server.go
vendor/golang.org/x/crypto/ssh/transport.go
vendor/modules.txt

/kind bug
fix: CVE-2023-48795
Fixes #
```
fix: CVE-2023-48795
```

fix: CVE-2023-48795

---

README.md

>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
It simply fixes a link in the Readme document.
Fixes #612 
```release-note
NONE
```

Fix documentation link for MicroK8S in readme

---

.github/workflows/trivy.yaml
release-tools/.github/dependabot.yaml
release-tools/.github/workflows/codespell.yml
release-tools/.github/workflows/trivy.yaml
release-tools/SIDECAR_RELEASE_PROCESS.md
release-tools/build.make
release-tools/generate-patch-release-notes.sh
release-tools/go-modules-targeted-update.sh
release-tools/prow.sh
release-tools/verify-logcheck.sh

chore: update release-tools to fix spelling error
Fixes #
```release-note
none
```

 chore: update release-tools to fix spelling error

---

Makefile
deploy/example/cloning/nginx-pod-restored-cloning.yaml
deploy/example/daemonset-nfs-ephemeral.yaml
deploy/example/deployment.yaml
deploy/example/nfs-provisioner/nfs-server.yaml
deploy/example/nfs-provisioner/nginx-pod.yaml
deploy/example/nginx-pod-inline-volume.yaml
deploy/example/nginx-pod-nfs.yaml
deploy/example/pvc-nfs-csi-dynamic.yaml
deploy/example/pvc-nfs-csi-static.yaml
deploy/example/snapshot/nginx-pod-restored-snapshot.yaml
deploy/example/statefulset.yaml
hack/verify-examples.sh

test: add default namespace in examples to fix e2e test failure
Fixes #
```release-note
none
```

test: add default namespace in examples to fix e2e test failure

---

support.md

doc: add support doc
Fixes #
```
none
```

doc: add support doc

---

Dockerfile

/kind feature
chore: upgrade to debian-base:bookworm-v1.0.4 base image
Fixes #
```
none
```

chore: upgrade to debian-base:bookworm-v1.0.4 base image

---

.github/workflows/trivy.yaml
go.mod

chore: upgrade golang version
```
==========================
Total: 3 (UNKNOWN: 0, LOW: 0, MEDIUM: 2, HIGH: 1, CRITICAL: 0)
┌─────────┬────────────────┬──────────┬────────┬───────────────────┬────────────────┬─────────────────────────────────────────────────────────────┐
│ Library │ Vulnerability  │ Severity │ Status │ Installed Version │ Fixed Version  │                            Title                            │
├─────────┼────────────────┼──────────┼────────┼───────────────────┼────────────────┼─────────────────────────────────────────────────────────────┤
│ stdlib  │ CVE-2024-[34](https://github.com/kubernetes-sigs/azurefile-csi-driver/actions/runs/10708260683/job/29848010527#step:6:35)156 │ HIGH …
```

chore: upgrade golang version

---

release-tools/build.make
release-tools/prow.sh

/kind bug
fix: build with go 1.22.5 to fix golang CVE
Fixes #
```
fix: build with go 1.22.5 to fix golang CVE
```

fix: build with go 1.22.5 to fix golang CVE

---

pkg/nfs/nodeserver.go
pkg/nfs/utils.go
pkg/nfs/utils_test.go

>
> /kind bug
> /kind design
> /kind flake
/kind bug
add timeout function on mount to fix stuck issue
Fixes #
```release-note
none
```

fix: add timeout on mount to fix stuck issue

---

go.mod
go.sum
vendor/golang.org/x/crypto/ssh/server.go
vendor/modules.txt

/kind bug
fix: CVE-2024-45337
Fixes #
```
fix: CVE-2024-45337
```

fix: CVE-2024-45337

---

test/sanity/run-test.sh

/kind cleanup
test: upgrade csi-test to v5.3.1
Fixes #
```
none
```

test: upgrade csi-test to v5.3.1

---

.github/workflows/trivy.yaml
pkg/nfs/nfs.go

/kind bug
fix: ondelete config no assigne
Fixes #858 
```release-note
fix: ondelete config no assigne
```

fix: ondelete config no assigne

---

.github/workflows/static.yaml
go.mod
pkg/nfs/controllerserver.go
pkg/nfs/controllerserver_test.go
pkg/nfs/utils.go
pkg/nfs/utils_test.go
release-tools/prow.sh

/kind cleanup
chore: use go1.24
Fixes #
```release-note
NONE
```

chore: use go1.24

---

deploy/csi-nfs-controller.yaml
deploy/csi-snapshot-controller.yaml

/kind feature
It's better to use a dynamic environment variable `POD_NAMESPACE` based on the value of the `metadata.namespace` field. This will simplify deployment for those who use kubectl/kustomize instead of Helm.
Fixes #
```release-note
none
```

feat: add POD_NAMESPACE environment var

---

.github/workflows/trivy.yaml

test: fix CVE-2025-47907 trivy test failure
Fixes #
```release-note
none
```

test: fix CVE-2025-47907 trivy test failure
